name: API CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: "12.x" 
    
    # PUSH TO SwaggerHUb     
    - run: npm install swaggerhub-cli -g && npm install --save pom-parser && npm install xml-js
           && npm install fs && npm install xml2js 
    # Run other automation here, such as tests or standardization checksffff
    - run: |
        export API_VERSION=$(node ././bin/readfile.js) &&
        export API_swagger_VERSION=$(swaggerhub api:get nouggg/demo-crud-application/$API_VERSION) && 
        swaggerhub api:create nouggg/demo-crud-application/$API_VERSION --file ././src/main/demo-crud-project.json --visibility public
      env:
         SWAGGERHUB_API_KEY: 4894a72a-3f04-4461-9ceb-31564ae7206f
         if: $API_VERSION !== $API_swagger_VERSION
         else if: 
          swaggerhub api:create nouggg/demo-crud-application/$API_VERSION --file ././src/main/demo-crud-project.json --visibility public --SWAGGERHUB_API_KEY 4894a72a-3f04-4461-9ceb-31564ae7206f
          
 
    - run: | 
        swaggerhub api:validate nouggg/demo-crud-application/$API_VERSION
      env:
         SWAGGERHUB_API_KEY: 4894a72a-3f04-4461-9ceb-31564ae7206f
       
