name: API CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: "12.x" 
    # validate
    - run: |
        npm install -g @apidevtools/swagger-cli && swagger-cli validate -v --file ././src/main/demo-crud-project.json
    # PUSH TO SwaggerHUb     
    - run: npm install swaggerhub-cli -g
    # Run other automation here, such as tests or standardization checks
    - run: |
        swaggerhub api:create nouggg/demo-crud-application1/$API_VERSION --file ././src/main/demo-crud-project.json --visibility public
      env:
         SWAGGERHUB_API_KEY: 4894a72a-3f04-4461-9ceb-31564ae7206f
         
    - run: |
        if : API version 'nouggg/demo-crud-application1/$API_VERSION' already exists
        swaggerhub api:create nouggg/demo-crud-application1/1.0 --file ././src/main/demo-crud-project.json --visibility public
      env:
         SWAGGERHUB_API_KEY: 4894a72a-3f04-4461-9ceb-31564ae7206f
  
    
    
    
