name: API CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: "12.x"   
     # PACKAGE APPLICATION
    - run: npm run-script readme.md
    - run: npm ci
    - run: npm pack
    # PUSH TO SwaggerHUb
    - run: 
        npm install swaggerhub-cli -g 
    # Run other automation here, such as tests or standardization checks
    - run: |
        swaggerhub api:create nousinfosystems/demo-crud-application1/1.0.0 --file ././demo-crud-project.json --visibility public
      env:
        SWAGGERHUB_API_KEY: 4894a72a-3f04-4461-9ceb-31564ae7206f
    
