name: API CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: "12.x" 

    # PUSH TO SwaggerHUb     
    - run: npm install swaggerhub-cli -g && npm install --save pom-parser && npm install --save-dev eslint@4
           
    # Run other automation here, such as tests or standardization checks
    - run: |
        export API_VERSION=$(node ././src/main/get-version.js) && \ 
        swaggerhub api:create nouggg/niwy-project/$API_VERSION --file ././src/main/demo-crud-project.json --visibility public   
      env:
         SWAGGERHUB_API_KEY: 4894a72a-3f04-4461-9ceb-31564ae7206f
         if: github.ref == 'refs/heads/main'
    - run: | 
        swaggerhub api:validate nouggg/demo-crud-application
        if: github.ref == 'refs/heads/main'
      env:
         SWAGGERHUB_API_KEY: 4894a72a-3f04-4461-9ceb-31564ae7206f
