name: API CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
    ################# Creating  API in Swagger hub ########################
  build : # update api in swagger hub
    runs-on: ubuntu-latest
    continue-on-error: true  
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: "12.x" 
    
    # PUSH TO SwaggerHub    
    - run: npm install swaggerhub-cli -g && npm install --save pom-parser && npm install xml-js
           && npm install fs && npm install xml2js && npm install js-yaml  
    ##### UPDATE SWAGGER API###########
        
      if: ${{ env.API_VERSION == env.API_swagger_VERSION }}
    - run: |
        export API_VERSION=$(node ././bin/readfile.js) &&
        swaggerhub api:update nouggg/demo-crud-application/$API_VERSION --file ././src/main/demo-crud-project.json --visibility public
        swaggerhub api:setdefault nouggg/demo-crud-application/$API_VERSION 
         
      if: ${{ env.API_VERSION != env.API_swagger_VERSION }} 
    - run: |
        export API_VERSION=$(node ././bin/readfile.js) &&
        swaggerhub api:create nouggg/demo-crud-application/$API_VERSION --file ././src/main/demo-crud-project.json --visibility public
        swaggerhub api:setdefault "nouggg/demo-crud-application/$API_VERSION"
      
       
    
