name: API CI

on:
  push:
    branches: [ main,dev ]
  pull_request:
    branches: [ main,dev ]
jobs:
  build : # update api in swagger hub
    runs-on: ubuntu-latest
    continue-on-error: true  
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: "12.x" 
    
    # Required installation   
    - run: npm install swaggerhub-cli -g && npm install fs && npm install xml2js && npm install js-yaml  
    
    ##### validating SWAGGER API Implemenation #############
    - run: 
        export API_VERSION=$(node ././bin/readfile.js) &&
        swaggerhub api:update nouggg/${GITHUB_REPOSITORY#*/}/$API_VERSION --file ././src/main/resources/api/demo-crud-project.json --visibility public
       || swaggerhub api:create nouggg/${GITHUB_REPOSITORY#*/}/$API_VERSION --file ././src/main/resources/api/demo-crud-project.json --visibility public
        
        swaggerhub api:setdefault "nouggg/${GITHUB_REPOSITORY#*/}/$API_VERSION"
        
      env: 
          SWAGGERHUB_API_KEY: 4894a72a-3f04-4461-9ceb-31564ae7206f
          
  
  
          
       
    
